services:
  bizzynetwork:
    build: .
    container_name: bizzy-backend
    environment:
      - PORT=5050
      - NODE_ENV=production
      - FB_STORAGE_BUCKET=${FB_STORAGE_BUCKET}
      - FB_REALTIME_DATABASE=${FB_REALTIME_DATABASE}
      - FRONTEND_URL=${FRONTEND_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - SERVER_URL=${SERVER_URL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - MAX_LOGIN_ATTEMPTS=${MAX_LOGIN_ATTEMPTS}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    networks:
      - nginx_proxy_net

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - nginx_proxy_net

networks:
  nginx_proxy_net:
    external: true
